# https://docs.flutter.dev/release/breaking-changes/flutter-generate-i10n-source
synthetic-package: false

arb-dir: lib/core/localization/l10n
template-arb-file: app_id.arb
output-localization-file: app_localizations.dart
